### ISSUE TITLE
请问这个怎么打包呢

### ISSUE THREAD

**Issue by zyxiaofeng** [stevenjoezhang/mimi-danmaku#41]
请问这个怎么打包呢

**Comment by zyxiaofeng** [comment]
npm run pack:mac
npm run pack:win

有没有这样指定平台打包的呢

**Comment by stevenjoezhang** [comment]
你好，打包的命令是
```
npm run build
```

见 https://github.com/stevenjoezhang/mimi-danmaku/blob/206b693defa65fd552fb6015a1bfbea2023686b0/package.json#L8

打包用的是 `electron-builder` ，默认情况下会生成 Windows 和 Mac 版本

**Comment by zyxiaofeng** [comment]
您好，是不是不能在mac  下 打包window呢

**Comment by zyxiaofeng** [comment]
感谢您的回答

**Comment by stevenjoezhang** [comment]
您好，我自己测试了一下，可以在 mac 下打包 windows 的版本
我用的是 macOS 10.15.5 和 Node.js 14.3.0，其他依赖见 package.json

**Comment by zyxiaofeng** [comment]
您好，使用npm run build吗，修改哪些配置，就可以了呢

**Comment by stevenjoezhang** [comment]
如果 `npm run build` 不行的话，试试
```
npm i --force
npx electron-builder --win
```
打包 Mac 版本需要配置 XCode 啥的，可能会出问题
具体可见参考文档： https://www.electron.build/cli
