### ISSUE TITLE
Electron version

### ISSUE THREAD

**Issue by AllanChain** [stevenjoezhang/mimi-danmaku#54]
现在 master 上是把 electron pin 在 v11.0.0 (#51)

但是该版本有 bug，打开弹幕窗口的时候报错 `screen.getAllDisplays is not a function` (electron/electron/issues/26610)

升级到 v11.1.1 后，又出现本该透明的弹幕窗口却是黑色的问题，暂未找到对应 issue。(tested on win10)

但是经测试发现 v11.0.3 没有问题。

所以我觉得应该改 electron version 为一个合适的版本

**Comment by stevenjoezhang** [comment]
谢谢，我会暂时将 electron 版本改为 v11.0.3。v11.1.1 出现的问题需要进一步测试。

**Comment by stevenjoezhang** [comment]
在 macOS 上没有复现窗口透明度问题，因此问题的来源可能是以下几处与 Windows 相关的改动
https://github.com/electron/electron/pull/26754
https://github.com/electron/electron/pull/26774
https://github.com/electron/electron/pull/26780

另见 https://github.com/electron/electron/issues/27286 和 https://github.com/electron/electron/issues/27265

**Comment by stevenjoezhang** [comment]
我这样改了之后没问题了 https://github.com/stevenjoezhang/mimi-danmaku/commit/6c39c181df57ffffd4b423e9b229d8194ec300a1
你有兴趣的话可以帮忙测试一下

**Comment by AllanChain** [comment]
测试过了，显示正常。不过窗口减几个像素的操作属实有点 tricky 😂

**Comment by stevenjoezhang** [comment]
现在升级到了 Electron v16，这个问题似乎解决了（在 Windows 11 21H2 22000.376 上测试正常）
